# This docker-compose.yml file is used to start services for testing.
# It is not used in the production environment.
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mirasurf-test-postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 